-- sex types
INSERT INTO sex_type (code, title) VALUES
	('male', 'Male'),
	('female', 'Female'),
	('none', 'Prefer not to say');

-- currency
INSERT INTO currency (code) VALUES
	('AED'), ('AFN'), ('ALL'), ('AMD'), ('AOA'), ('ARS'), ('AUD'), ('AWG'), ('AZN'),
	('BAM'), ('BBD'), ('BDT'), ('BHD'), ('BIF'), ('BMD'), ('BND'), ('BOB'), ('BOV'),
	('BRL'), ('BSD'), ('BTN'), ('BWP'), ('BYN'), ('BZD'), ('CAD'), ('CDF'), ('CHE'),
	('CHF'), ('CHW'), ('CLF'), ('CLP'), ('CNY'), ('COP'), ('COU'), ('CRC'), ('CUP'),
	('CVE'), ('CZK'), ('DJF'), ('DKK'), ('DOP'), ('DZD'), ('EGP'), ('ERN'), ('ETB'),
	('EUR'), ('FJD'), ('FKP'), ('GBP'), ('GEL'), ('GHS'), ('GIP'), ('GMD'), ('GNF'),
	('GTQ'), ('GYD'), ('HKD'), ('HNL'), ('HTG'), ('HUF'), ('IDR'), ('ILS'), ('INR'),
	('IQD'), ('IRR'), ('ISK'), ('JMD'), ('JOD'), ('JPY'), ('KES'), ('KGS'), ('KHR'),
	('KMF'), ('KPW'), ('KRW'), ('KWD'), ('KYD'), ('KZT'), ('LAK'), ('LBP'), ('LKR'),
	('LRD'), ('LSL'), ('LYD'), ('MAD'), ('MDL'), ('MGA'), ('MKD'), ('MMK'), ('MNT'),
	('MOP'), ('MRU'), ('MUR'), ('MVR'), ('MWK'), ('MXN'), ('MXV'), ('MYR'), ('MZN'),
	('NAD'), ('NGN'), ('NIO'), ('NOK'), ('NPR'), ('NZD'), ('OMR'), ('PAB'), ('PEN'),
	('PGK'), ('PHP'), ('PKR'), ('PLN'), ('PYG'), ('QAR'), ('RON'), ('RSD'), ('RUB'),
	('RWF'), ('SAR'), ('SBD'), ('SCR'), ('SDG'), ('SEK'), ('SGD'), ('SHP'), ('SLE'),
	('SOS'), ('SRD'), ('SSP'), ('STN'), ('SVC'), ('SYP'), ('SZL'), ('THB'), ('TJS'),
	('TMT'), ('TND'), ('TOP'), ('TRY'), ('TTD'), ('TWD'), ('TZS'), ('UAH'), ('UGX'),
	('USD'), ('USN'), ('UYI'), ('UYU'), ('UYW'), ('UZS'), ('VED'), ('VES'), ('VND'),
	('VUV'), ('WST'), ('XAD'), ('XAF'), ('XAG'), ('XAU'), ('XBA'), ('XBB'), ('XBC'),
	('XBD'), ('XCD'), ('XCG'), ('XDR'), ('XOF'), ('XPD'), ('XPF'), ('XPT'), ('XSU'),
	('XTS'), ('XUA'), ('XXX'), ('YER'), ('ZAR'), ('ZMW'), ('ZWG');
	
-- country and currency mapping (first ISO code only)
INSERT INTO country (code, name, currency_id) VALUES
    ('AF', 'Afghanistan', (SELECT id FROM currency WHERE code = 'AFN')),
    ('AL', 'Albania', (SELECT id FROM currency WHERE code = 'ALL')),
    ('DZ', 'Algeria', (SELECT id FROM currency WHERE code = 'DZD')),
    ('AS', 'American Samoa', (SELECT id FROM currency WHERE code = 'USD')),
    ('AD', 'Andorra', (SELECT id FROM currency WHERE code = 'EUR')),
    ('AO', 'Angola', (SELECT id FROM currency WHERE code = 'AOA')),
    ('AI', 'Anguilla', (SELECT id FROM currency WHERE code = 'XCD')),
    ('AG', 'Antigua and Barbuda', (SELECT id FROM currency WHERE code = 'XCD')),
    ('AR', 'Argentina', (SELECT id FROM currency WHERE code = 'ARS')),
    ('AM', 'Armenia', (SELECT id FROM currency WHERE code = 'AMD')),
    ('AW', 'Aruba', (SELECT id FROM currency WHERE code = 'AWG')),
    ('AU', 'Australia', (SELECT id FROM currency WHERE code = 'AUD')),
    ('AT', 'Austria', (SELECT id FROM currency WHERE code = 'EUR')),
    ('AZ', 'Azerbaijan', (SELECT id FROM currency WHERE code = 'AZN')),
    ('BS', 'Bahamas', (SELECT id FROM currency WHERE code = 'BSD')),
    ('BH', 'Bahrain', (SELECT id FROM currency WHERE code = 'BHD')),
    ('BD', 'Bangladesh', (SELECT id FROM currency WHERE code = 'BDT')),
    ('BB', 'Barbados', (SELECT id FROM currency WHERE code = 'BBD')),
    ('BY', 'Belarus', (SELECT id FROM currency WHERE code = 'BYN')),
    ('BE', 'Belgium', (SELECT id FROM currency WHERE code = 'EUR')),
    ('BZ', 'Belize', (SELECT id FROM currency WHERE code = 'BZD')),
    ('BJ', 'Benin', (SELECT id FROM currency WHERE code = 'XOF')),
    ('BM', 'Bermuda', (SELECT id FROM currency WHERE code = 'BMD')),
    ('BT', 'Bhutan', (SELECT id FROM currency WHERE code = 'BTN')),
    ('BO', 'Bolivia', (SELECT id FROM currency WHERE code = 'BOB')),
    ('BA', 'Bosnia and Herzegovina', (SELECT id FROM currency WHERE code = 'BAM')),
    ('BW', 'Botswana', (SELECT id FROM currency WHERE code = 'BWP')),
    ('BR', 'Brazil', (SELECT id FROM currency WHERE code = 'BRL')),
    ('VG', 'British Virgin Islands', (SELECT id FROM currency WHERE code = 'USD')),
    ('BN', 'Brunei', (SELECT id FROM currency WHERE code = 'BND')),
    ('BG', 'Bulgaria', (SELECT id FROM currency WHERE code = 'EUR')),
    ('BF', 'Burkina Faso', (SELECT id FROM currency WHERE code = 'XOF')),
    ('BI', 'Burundi', (SELECT id FROM currency WHERE code = 'BIF')),
    ('CV', 'Cabo Verde', (SELECT id FROM currency WHERE code = 'CVE')),
    ('KH', 'Cambodia', (SELECT id FROM currency WHERE code = 'KHR')),
    ('CM', 'Cameroon', (SELECT id FROM currency WHERE code = 'XAF')),
    ('CA', 'Canada', (SELECT id FROM currency WHERE code = 'CAD')),
    ('BQ', 'Caribbean Netherlands', (SELECT id FROM currency WHERE code = 'USD')),
    ('KY', 'Cayman Islands', (SELECT id FROM currency WHERE code = 'KYD')),
    ('CF', 'Central African Republic', (SELECT id FROM currency WHERE code = 'XAF')),
    ('TD', 'Chad', (SELECT id FROM currency WHERE code = 'XAF')),
    ('CL', 'Chile', (SELECT id FROM currency WHERE code = 'CLP')),
    ('CN', 'China', (SELECT id FROM currency WHERE code = 'CNY')),
    ('CO', 'Colombia', (SELECT id FROM currency WHERE code = 'COP')),
    ('KM', 'Comoros', (SELECT id FROM currency WHERE code = 'KMF')),
    ('CG', 'Congo (Congo-Brazzaville)', (SELECT id FROM currency WHERE code = 'XAF')),
    ('CK', 'Cook Islands', (SELECT id FROM currency WHERE code = 'NZD')),
    ('CR', 'Costa Rica', (SELECT id FROM currency WHERE code = 'CRC')),
    ('CI', 'Cote d''Ivoire', (SELECT id FROM currency WHERE code = 'XOF')),
    ('HR', 'Croatia', (SELECT id FROM currency WHERE code = 'EUR')),
    ('CU', 'Cuba', (SELECT id FROM currency WHERE code = 'CUP')),
    ('CW', 'Curacao', (SELECT id FROM currency WHERE code = 'XCG')),
    ('CY', 'Cyprus', (SELECT id FROM currency WHERE code = 'EUR')),
    ('CZ', 'Czechia (Czech Republic)', (SELECT id FROM currency WHERE code = 'CZK')),
    ('CD', 'Democratic Republic of the Congo', (SELECT id FROM currency WHERE code = 'CDF')),
    ('DK', 'Denmark', (SELECT id FROM currency WHERE code = 'DKK')),
    ('DJ', 'Djibouti', (SELECT id FROM currency WHERE code = 'DJF')),
    ('DM', 'Dominica', (SELECT id FROM currency WHERE code = 'XCD')),
    ('DO', 'Dominican Republic', (SELECT id FROM currency WHERE code = 'DOP')),
    ('EC', 'Ecuador', (SELECT id FROM currency WHERE code = 'USD')),
    ('EG', 'Egypt', (SELECT id FROM currency WHERE code = 'EGP')),
    ('SV', 'El Salvador', (SELECT id FROM currency WHERE code = 'USD')),
    ('GQ', 'Equatorial Guinea', (SELECT id FROM currency WHERE code = 'XAF')),
    ('ER', 'Eritrea', (SELECT id FROM currency WHERE code = 'ERN')),
    ('EE', 'Estonia', (SELECT id FROM currency WHERE code = 'EUR')),
    ('SZ', 'Eswatini', (SELECT id FROM currency WHERE code = 'SZL')),
    ('ET', 'Ethiopia', (SELECT id FROM currency WHERE code = 'ETB')),
    ('FK', 'Falkland Islands', (SELECT id FROM currency WHERE code = 'FKP')),
    ('FO', 'Faroe Islands', (SELECT id FROM currency WHERE code = 'DKK')),
    ('FJ', 'Fiji', (SELECT id FROM currency WHERE code = 'FJD')),
    ('FI', 'Finland', (SELECT id FROM currency WHERE code = 'EUR')),
    ('FR', 'France', (SELECT id FROM currency WHERE code = 'EUR')),
    ('GF', 'French Guiana', (SELECT id FROM currency WHERE code = 'EUR')),
    ('PF', 'French Polynesia', (SELECT id FROM currency WHERE code = 'XPF')),
    ('GA', 'Gabon', (SELECT id FROM currency WHERE code = 'XAF')),
    ('GM', 'Gambia', (SELECT id FROM currency WHERE code = 'GMD')),
    ('GE', 'Georgia', (SELECT id FROM currency WHERE code = 'GEL')),
    ('DE', 'Germany', (SELECT id FROM currency WHERE code = 'EUR')),
    ('GH', 'Ghana', (SELECT id FROM currency WHERE code = 'GHS')),
    ('GI', 'Gibraltar', (SELECT id FROM currency WHERE code = 'GIP')),
    ('GR', 'Greece', (SELECT id FROM currency WHERE code = 'EUR')),
    ('GL', 'Greenland', (SELECT id FROM currency WHERE code = 'DKK')),
    ('GD', 'Grenada', (SELECT id FROM currency WHERE code = 'XCD')),
    ('GP', 'Guadeloupe', (SELECT id FROM currency WHERE code = 'EUR')),
    ('GU', 'Guam', (SELECT id FROM currency WHERE code = 'USD')),
    ('GT', 'Guatemala', (SELECT id FROM currency WHERE code = 'GTQ')),
    ('GN', 'Guinea', (SELECT id FROM currency WHERE code = 'GNF')),
    ('GW', 'Guinea-Bissau', (SELECT id FROM currency WHERE code = 'XOF')),
    ('GY', 'Guyana', (SELECT id FROM currency WHERE code = 'GYD')),
    ('HT', 'Haiti', (SELECT id FROM currency WHERE code = 'HTG')),
    ('VA', 'Holy See', (SELECT id FROM currency WHERE code = 'EUR')),
    ('HN', 'Honduras', (SELECT id FROM currency WHERE code = 'HNL')),
    ('HK', 'Hong Kong', (SELECT id FROM currency WHERE code = 'HKD')),
    ('HU', 'Hungary', (SELECT id FROM currency WHERE code = 'HUF')),
    ('IS', 'Iceland', (SELECT id FROM currency WHERE code = 'ISK')),
    ('IN', 'India', (SELECT id FROM currency WHERE code = 'INR')),
    ('ID', 'Indonesia', (SELECT id FROM currency WHERE code = 'IDR')),
    ('IR', 'Iran', (SELECT id FROM currency WHERE code = 'IRR')),
    ('IQ', 'Iraq', (SELECT id FROM currency WHERE code = 'IQD')),
    ('IE', 'Ireland', (SELECT id FROM currency WHERE code = 'EUR')),
    ('IM', 'Isle of Man', (SELECT id FROM currency WHERE code = 'GBP')),
    ('IL', 'Israel', (SELECT id FROM currency WHERE code = 'ILS')),
    ('IT', 'Italy', (SELECT id FROM currency WHERE code = 'EUR')),
    ('JM', 'Jamaica', (SELECT id FROM currency WHERE code = 'JMD')),
    ('JP', 'Japan', (SELECT id FROM currency WHERE code = 'JPY')),
    ('JO', 'Jordan', (SELECT id FROM currency WHERE code = 'JOD')),
    ('KZ', 'Kazakhstan', (SELECT id FROM currency WHERE code = 'KZT')),
    ('KE', 'Kenya', (SELECT id FROM currency WHERE code = 'KES')),
    ('KI', 'Kiribati', (SELECT id FROM currency WHERE code = 'AUD')),
    ('KW', 'Kuwait', (SELECT id FROM currency WHERE code = 'KWD')),
    ('KG', 'Kyrgyzstan', (SELECT id FROM currency WHERE code = 'KGS')),
    ('LA', 'Laos', (SELECT id FROM currency WHERE code = 'LAK')),
    ('LV', 'Latvia', (SELECT id FROM currency WHERE code = 'EUR')),
    ('LB', 'Lebanon', (SELECT id FROM currency WHERE code = 'LBP')),
    ('LS', 'Lesotho', (SELECT id FROM currency WHERE code = 'LSL')),
    ('LR', 'Liberia', (SELECT id FROM currency WHERE code = 'LRD')),
    ('LY', 'Libya', (SELECT id FROM currency WHERE code = 'LYD')),
    ('LI', 'Liechtenstein', (SELECT id FROM currency WHERE code = 'CHF')),
    ('LT', 'Lithuania', (SELECT id FROM currency WHERE code = 'EUR')),
    ('LU', 'Luxembourg', (SELECT id FROM currency WHERE code = 'EUR')),
    ('MO', 'Macao', (SELECT id FROM currency WHERE code = 'MOP')),
    ('MG', 'Madagascar', (SELECT id FROM currency WHERE code = 'MGA')),
    ('MW', 'Malawi', (SELECT id FROM currency WHERE code = 'MWK')),
    ('MY', 'Malaysia', (SELECT id FROM currency WHERE code = 'MYR')),
    ('MV', 'Maldives', (SELECT id FROM currency WHERE code = 'MVR')),
    ('ML', 'Mali', (SELECT id FROM currency WHERE code = 'XOF')),
    ('MT', 'Malta', (SELECT id FROM currency WHERE code = 'EUR')),
    ('MH', 'Marshall Islands', (SELECT id FROM currency WHERE code = 'USD')),
    ('MQ', 'Martinique', (SELECT id FROM currency WHERE code = 'EUR')),
    ('MR', 'Mauritania', (SELECT id FROM currency WHERE code = 'MRU')),
    ('MU', 'Mauritius', (SELECT id FROM currency WHERE code = 'MUR')),
    ('YT', 'Mayotte', (SELECT id FROM currency WHERE code = 'EUR')),
    ('MX', 'Mexico', (SELECT id FROM currency WHERE code = 'MXN')),
    ('FM', 'Micronesia', (SELECT id FROM currency WHERE code = 'USD')),
    ('MD', 'Moldova', (SELECT id FROM currency WHERE code = 'MDL')),
    ('MC', 'Monaco', (SELECT id FROM currency WHERE code = 'EUR')),
    ('MN', 'Mongolia', (SELECT id FROM currency WHERE code = 'MNT')),
    ('ME', 'Montenegro', (SELECT id FROM currency WHERE code = 'EUR')),
    ('MS', 'Montserrat', (SELECT id FROM currency WHERE code = 'XCD')),
    ('MA', 'Morocco', (SELECT id FROM currency WHERE code = 'MAD')),
    ('MZ', 'Mozambique', (SELECT id FROM currency WHERE code = 'MZN')),
    ('MM', 'Myanmar (formerly Burma)', (SELECT id FROM currency WHERE code = 'MMK')),
    ('NA', 'Namibia', (SELECT id FROM currency WHERE code = 'NAD')),
    ('NR', 'Nauru', (SELECT id FROM currency WHERE code = 'AUD')),
    ('NP', 'Nepal', (SELECT id FROM currency WHERE code = 'NPR')),
    ('NL', 'Netherlands', (SELECT id FROM currency WHERE code = 'EUR')),
    ('NC', 'New Caledonia', (SELECT id FROM currency WHERE code = 'XPF')),
    ('NZ', 'New Zealand', (SELECT id FROM currency WHERE code = 'NZD')),
    ('NI', 'Nicaragua', (SELECT id FROM currency WHERE code = 'NIO')),
    ('NE', 'Niger', (SELECT id FROM currency WHERE code = 'XOF')),
    ('NG', 'Nigeria', (SELECT id FROM currency WHERE code = 'NGN')),
    ('NU', 'Niue', (SELECT id FROM currency WHERE code = 'NZD')),
    ('KP', 'North Korea', (SELECT id FROM currency WHERE code = 'KPW')),
    ('MK', 'North Macedonia', (SELECT id FROM currency WHERE code = 'MKD')),
    ('MP', 'Northern Mariana Islands', (SELECT id FROM currency WHERE code = 'USD')),
    ('NO', 'Norway', (SELECT id FROM currency WHERE code = 'NOK')),
    ('OM', 'Oman', (SELECT id FROM currency WHERE code = 'OMR')),
    ('PK', 'Pakistan', (SELECT id FROM currency WHERE code = 'PKR')),
    ('PW', 'Palau', (SELECT id FROM currency WHERE code = 'USD')),
    ('PS', 'Palestine State', (SELECT id FROM currency WHERE code = 'ILS')),
    ('PA', 'Panama', (SELECT id FROM currency WHERE code = 'PAB')),
    ('PG', 'Papua New Guinea', (SELECT id FROM currency WHERE code = 'PGK')),
    ('PY', 'Paraguay', (SELECT id FROM currency WHERE code = 'PYG')),
    ('PE', 'Peru', (SELECT id FROM currency WHERE code = 'PEN')),
    ('PH', 'Philippines', (SELECT id FROM currency WHERE code = 'PHP')),
    ('PL', 'Poland', (SELECT id FROM currency WHERE code = 'PLN')),
    ('PT', 'Portugal', (SELECT id FROM currency WHERE code = 'EUR')),
    ('PR', 'Puerto Rico', (SELECT id FROM currency WHERE code = 'USD')),
    ('QA', 'Qatar', (SELECT id FROM currency WHERE code = 'QAR')),
    ('RE', 'Reunion', (SELECT id FROM currency WHERE code = 'EUR')),
    ('RO', 'Romania', (SELECT id FROM currency WHERE code = 'RON')),
    ('RU', 'Russia', (SELECT id FROM currency WHERE code = 'RUB')),
    ('RW', 'Rwanda', (SELECT id FROM currency WHERE code = 'RWF')),
    ('BL', 'Saint Barthelemy', (SELECT id FROM currency WHERE code = 'EUR')),
    ('SH', 'Saint Helena', (SELECT id FROM currency WHERE code = 'SHP')),
    ('KN', 'Saint Kitts and Nevis', (SELECT id FROM currency WHERE code = 'XCD')),
    ('LC', 'Saint Lucia', (SELECT id FROM currency WHERE code = 'XCD')),
    ('MF', 'Saint Martin', (SELECT id FROM currency WHERE code = 'EUR')),
    ('PM', 'Saint Pierre and Miquelon', (SELECT id FROM currency WHERE code = 'EUR')),
    ('VC', 'Saint Vincent and the Grenadines', (SELECT id FROM currency WHERE code = 'XCD')),
    ('WS', 'Samoa', (SELECT id FROM currency WHERE code = 'WST')),
    ('SM', 'San Marino', (SELECT id FROM currency WHERE code = 'EUR')),
    ('ST', 'Sao Tome and Principe', (SELECT id FROM currency WHERE code = 'STN')),
    ('SA', 'Saudi Arabia', (SELECT id FROM currency WHERE code = 'SAR')),
    ('SN', 'Senegal', (SELECT id FROM currency WHERE code = 'XOF')),
    ('RS', 'Serbia', (SELECT id FROM currency WHERE code = 'RSD')),
    ('SC', 'Seychelles', (SELECT id FROM currency WHERE code = 'SCR')),
    ('SL', 'Sierra Leone', (SELECT id FROM currency WHERE code = 'SLE')),
    ('SG', 'Singapore', (SELECT id FROM currency WHERE code = 'SGD')),
    ('SX', 'Sint Maarten', (SELECT id FROM currency WHERE code = 'XCG')),
    ('SK', 'Slovakia', (SELECT id FROM currency WHERE code = 'EUR')),
    ('SI', 'Slovenia', (SELECT id FROM currency WHERE code = 'EUR')),
    ('SB', 'Solomon Islands', (SELECT id FROM currency WHERE code = 'SBD')),
    ('SO', 'Somalia', (SELECT id FROM currency WHERE code = 'SOS')),
    ('ZA', 'South Africa', (SELECT id FROM currency WHERE code = 'ZAR')),
    ('KR', 'South Korea', (SELECT id FROM currency WHERE code = 'KRW')),
    ('SS', 'South Sudan', (SELECT id FROM currency WHERE code = 'SSP')),
    ('ES', 'Spain', (SELECT id FROM currency WHERE code = 'EUR')),
    ('LK', 'Sri Lanka', (SELECT id FROM currency WHERE code = 'LKR')),
    ('SD', 'Sudan', (SELECT id FROM currency WHERE code = 'SDG')),
    ('SR', 'Suriname', (SELECT id FROM currency WHERE code = 'SRD')),
    ('SE', 'Sweden', (SELECT id FROM currency WHERE code = 'SEK')),
    ('CH', 'Switzerland', (SELECT id FROM currency WHERE code = 'CHF')),
    ('SY', 'Syria', (SELECT id FROM currency WHERE code = 'SYP')),
    ('TW', 'Taiwan', (SELECT id FROM currency WHERE code = 'TWD')),
    ('TJ', 'Tajikistan', (SELECT id FROM currency WHERE code = 'TJS')),
    ('TZ', 'Tanzania', (SELECT id FROM currency WHERE code = 'TZS')),
    ('TH', 'Thailand', (SELECT id FROM currency WHERE code = 'THB')),
    ('TL', 'Timor-Leste', (SELECT id FROM currency WHERE code = 'USD')),
    ('TG', 'Togo', (SELECT id FROM currency WHERE code = 'XOF')),
    ('TK', 'Tokelau', (SELECT id FROM currency WHERE code = 'NZD')),
    ('TO', 'Tonga', (SELECT id FROM currency WHERE code = 'TOP')),
    ('TT', 'Trinidad and Tobago', (SELECT id FROM currency WHERE code = 'TTD')),
    ('TN', 'Tunisia', (SELECT id FROM currency WHERE code = 'TND')),
    ('TR', 'Turkey', (SELECT id FROM currency WHERE code = 'TRY')),
    ('TM', 'Turkmenistan', (SELECT id FROM currency WHERE code = 'TMT')),
    ('TC', 'Turks and Caicos', (SELECT id FROM currency WHERE code = 'USD')),
    ('TV', 'Tuvalu', (SELECT id FROM currency WHERE code = 'AUD')),
    ('UG', 'Uganda', (SELECT id FROM currency WHERE code = 'UGX')),
    ('UA', 'Ukraine', (SELECT id FROM currency WHERE code = 'UAH')),
    ('AE', 'United Arab Emirates', (SELECT id FROM currency WHERE code = 'AED')),
    ('GB', 'United Kingdom', (SELECT id FROM currency WHERE code = 'GBP')),
    ('US', 'United States of America', (SELECT id FROM currency WHERE code = 'USD')),
    ('UY', 'Uruguay', (SELECT id FROM currency WHERE code = 'UYU')),
    ('VI', 'US Virgin Islands', (SELECT id FROM currency WHERE code = 'USD')),
    ('UZ', 'Uzbekistan', (SELECT id FROM currency WHERE code = 'UZS')),
    ('VU', 'Vanuatu', (SELECT id FROM currency WHERE code = 'VUV')),
    ('VE', 'Venezuela', (SELECT id FROM currency WHERE code = 'VES')),
    ('VN', 'Vietnam', (SELECT id FROM currency WHERE code = 'VND')),
    ('WF', 'Wallis and Futuna', (SELECT id FROM currency WHERE code = 'XPF')),
    ('EH', 'Western Sahara', (SELECT id FROM currency WHERE code = 'MAD')),
    ('YE', 'Yemen', (SELECT id FROM currency WHERE code = 'YER')),
    ('ZM', 'Zambia', (SELECT id FROM currency WHERE code = 'ZMW')),
    ('ZW', 'Zimbabwe', (SELECT id FROM currency WHERE code = 'ZWG'));

-- life expectancy (2026), value order: none, female, male
INSERT INTO life_expectancy_estimation (age, country_id, sex_type_id) VALUES
	(86.73, (SELECT id FROM country WHERE code = 'MC'), (SELECT id FROM sex_type WHERE code = 'none')),
	(88.85, (SELECT id FROM country WHERE code = 'MC'), (SELECT id FROM sex_type WHERE code = 'female')),
	(84.78, (SELECT id FROM country WHERE code = 'MC'), (SELECT id FROM sex_type WHERE code = 'male')),
	(86.03, (SELECT id FROM country WHERE code = 'SM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(87.44, (SELECT id FROM country WHERE code = 'SM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(84.54, (SELECT id FROM country WHERE code = 'SM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(85.9, (SELECT id FROM country WHERE code = 'HK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(88.51, (SELECT id FROM country WHERE code = 'HK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(83.22, (SELECT id FROM country WHERE code = 'HK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(85.15, (SELECT id FROM country WHERE code = 'JP'), (SELECT id FROM sex_type WHERE code = 'none')),
	(88.18, (SELECT id FROM country WHERE code = 'JP'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.13, (SELECT id FROM country WHERE code = 'JP'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.64, (SELECT id FROM country WHERE code = 'KR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(87.51, (SELECT id FROM country WHERE code = 'KR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.56, (SELECT id FROM country WHERE code = 'KR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.63, (SELECT id FROM country WHERE code = 'BL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(87.14, (SELECT id FROM country WHERE code = 'BL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.81, (SELECT id FROM country WHERE code = 'BL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.46, (SELECT id FROM country WHERE code = 'AD'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.48, (SELECT id FROM country WHERE code = 'AD'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.55, (SELECT id FROM country WHERE code = 'AD'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.44, (SELECT id FROM country WHERE code = 'PF'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.86, (SELECT id FROM country WHERE code = 'PF'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.16, (SELECT id FROM country WHERE code = 'PF'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.37, (SELECT id FROM country WHERE code = 'CH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.2, (SELECT id FROM country WHERE code = 'CH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.48, (SELECT id FROM country WHERE code = 'CH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.34, (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.07, (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.59, (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.18, (SELECT id FROM country WHERE code = 'IT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.13, (SELECT id FROM country WHERE code = 'IT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.12, (SELECT id FROM country WHERE code = 'IT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.13, (SELECT id FROM country WHERE code = 'SG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.6, (SELECT id FROM country WHERE code = 'SG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.67, (SELECT id FROM country WHERE code = 'SG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.08, (SELECT id FROM country WHERE code = 'ES'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.71, (SELECT id FROM country WHERE code = 'ES'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.4, (SELECT id FROM country WHERE code = 'ES'), (SELECT id FROM sex_type WHERE code = 'male')),
	(84.06, (SELECT id FROM country WHERE code = 'LI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.64, (SELECT id FROM country WHERE code = 'LI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.39, (SELECT id FROM country WHERE code = 'LI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.92, (SELECT id FROM country WHERE code = 'RE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.68, (SELECT id FROM country WHERE code = 'RE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.94, (SELECT id FROM country WHERE code = 'RE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.9, (SELECT id FROM country WHERE code = 'GI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.45, (SELECT id FROM country WHERE code = 'GI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.33, (SELECT id FROM country WHERE code = 'GI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.78, (SELECT id FROM country WHERE code = 'MT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.63, (SELECT id FROM country WHERE code = 'MT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.88, (SELECT id FROM country WHERE code = 'MT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.76, (SELECT id FROM country WHERE code = 'NO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.21, (SELECT id FROM country WHERE code = 'NO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.31, (SELECT id FROM country WHERE code = 'NO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.73, (SELECT id FROM country WHERE code = 'SE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.45, (SELECT id FROM country WHERE code = 'SE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.03, (SELECT id FROM country WHERE code = 'SE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.7, (SELECT id FROM country WHERE code = 'FR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.42, (SELECT id FROM country WHERE code = 'FR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.86, (SELECT id FROM country WHERE code = 'FR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.6, (SELECT id FROM country WHERE code = 'MO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.64, (SELECT id FROM country WHERE code = 'MO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.47, (SELECT id FROM country WHERE code = 'MO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.41, (SELECT id FROM country WHERE code = 'VA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.44, (SELECT id FROM country WHERE code = 'VA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.31, (SELECT id FROM country WHERE code = 'VA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.39, (SELECT id FROM country WHERE code = 'AE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.55, (SELECT id FROM country WHERE code = 'AE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.56, (SELECT id FROM country WHERE code = 'AE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.3, (SELECT id FROM country WHERE code = 'IS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.69, (SELECT id FROM country WHERE code = 'IS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.96, (SELECT id FROM country WHERE code = 'IS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.05, (SELECT id FROM country WHERE code = 'CA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.16, (SELECT id FROM country WHERE code = 'CA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.94, (SELECT id FROM country WHERE code = 'CA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(83.04, (SELECT id FROM country WHERE code = 'MQ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.95, (SELECT id FROM country WHERE code = 'MQ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.81, (SELECT id FROM country WHERE code = 'MQ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.92, (SELECT id FROM country WHERE code = 'IE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.86, (SELECT id FROM country WHERE code = 'IE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.01, (SELECT id FROM country WHERE code = 'IE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.9, (SELECT id FROM country WHERE code = 'IL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.94, (SELECT id FROM country WHERE code = 'IL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.8, (SELECT id FROM country WHERE code = 'IL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.89, (SELECT id FROM country WHERE code = 'PT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.51, (SELECT id FROM country WHERE code = 'PT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.11, (SELECT id FROM country WHERE code = 'PT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.83, (SELECT id FROM country WHERE code = 'QA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.72, (SELECT id FROM country WHERE code = 'QA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(82.13, (SELECT id FROM country WHERE code = 'QA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.83, (SELECT id FROM country WHERE code = 'BM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(86.14, (SELECT id FROM country WHERE code = 'BM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.44, (SELECT id FROM country WHERE code = 'BM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.64, (SELECT id FROM country WHERE code = 'LU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.17, (SELECT id FROM country WHERE code = 'LU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.08, (SELECT id FROM country WHERE code = 'LU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.61, (SELECT id FROM country WHERE code = 'NL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.1, (SELECT id FROM country WHERE code = 'NL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.09, (SELECT id FROM country WHERE code = 'NL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.59, (SELECT id FROM country WHERE code = 'BE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.69, (SELECT id FROM country WHERE code = 'BE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.46, (SELECT id FROM country WHERE code = 'BE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.56, (SELECT id FROM country WHERE code = 'GP'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.88, (SELECT id FROM country WHERE code = 'GP'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.75, (SELECT id FROM country WHERE code = 'GP'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.52, (SELECT id FROM country WHERE code = 'NZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.1, (SELECT id FROM country WHERE code = 'NZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.93, (SELECT id FROM country WHERE code = 'NZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.45, (SELECT id FROM country WHERE code = 'AT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.69, (SELECT id FROM country WHERE code = 'AT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.17, (SELECT id FROM country WHERE code = 'AT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.4, (SELECT id FROM country WHERE code = 'FI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.02, (SELECT id FROM country WHERE code = 'FI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.8, (SELECT id FROM country WHERE code = 'FI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.39, (SELECT id FROM country WHERE code = 'GR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.73, (SELECT id FROM country WHERE code = 'GR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.95, (SELECT id FROM country WHERE code = 'GR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.39, (SELECT id FROM country WHERE code = 'DK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.19, (SELECT id FROM country WHERE code = 'DK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.57, (SELECT id FROM country WHERE code = 'DK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.27, (SELECT id FROM country WHERE code = 'PR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(85.63, (SELECT id FROM country WHERE code = 'PR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.72, (SELECT id FROM country WHERE code = 'PR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.15, (SELECT id FROM country WHERE code = 'CY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.05, (SELECT id FROM country WHERE code = 'CY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.24, (SELECT id FROM country WHERE code = 'CY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(82.09, (SELECT id FROM country WHERE code = 'SI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.69, (SELECT id FROM country WHERE code = 'SI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.54, (SELECT id FROM country WHERE code = 'SI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.86, (SELECT id FROM country WHERE code = 'DE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.11, (SELECT id FROM country WHERE code = 'DE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.62, (SELECT id FROM country WHERE code = 'DE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.75, (SELECT id FROM country WHERE code = 'GB'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.57, (SELECT id FROM country WHERE code = 'GB'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.89, (SELECT id FROM country WHERE code = 'GB'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.74, (SELECT id FROM country WHERE code = 'BH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.4, (SELECT id FROM country WHERE code = 'BH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(81.21, (SELECT id FROM country WHERE code = 'BH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.73, (SELECT id FROM country WHERE code = 'MV'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.34, (SELECT id FROM country WHERE code = 'MV'), (SELECT id FROM sex_type WHERE code = 'female')),
	(80.44, (SELECT id FROM country WHERE code = 'MV'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.72, (SELECT id FROM country WHERE code = 'CL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.51, (SELECT id FROM country WHERE code = 'CL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.88, (SELECT id FROM country WHERE code = 'CL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.39, (SELECT id FROM country WHERE code = 'IM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.4, (SELECT id FROM country WHERE code = 'IM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.42, (SELECT id FROM country WHERE code = 'IM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.38, (SELECT id FROM country WHERE code = 'CR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.87, (SELECT id FROM country WHERE code = 'CR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.84, (SELECT id FROM country WHERE code = 'CR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(81.14, (SELECT id FROM country WHERE code = 'TW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.02, (SELECT id FROM country WHERE code = 'TW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.32, (SELECT id FROM country WHERE code = 'TW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.97, (SELECT id FROM country WHERE code = 'KW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.3, (SELECT id FROM country WHERE code = 'KW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.83, (SELECT id FROM country WHERE code = 'KW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.9, (SELECT id FROM country WHERE code = 'KY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.28, (SELECT id FROM country WHERE code = 'KY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.62, (SELECT id FROM country WHERE code = 'KY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.85, (SELECT id FROM country WHERE code = 'MF'), (SELECT id FROM sex_type WHERE code = 'none')),
	(84.21, (SELECT id FROM country WHERE code = 'MF'), (SELECT id FROM sex_type WHERE code = 'female')),
	(77.43, (SELECT id FROM country WHERE code = 'MF'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.81, (SELECT id FROM country WHERE code = 'FO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.02, (SELECT id FROM country WHERE code = 'FO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.87, (SELECT id FROM country WHERE code = 'FO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.65, (SELECT id FROM country WHERE code = 'OM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.36, (SELECT id FROM country WHERE code = 'OM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(79.17, (SELECT id FROM country WHERE code = 'OM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.25, (SELECT id FROM country WHERE code = 'CZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.96, (SELECT id FROM country WHERE code = 'CZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(77.53, (SELECT id FROM country WHERE code = 'CZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.15, (SELECT id FROM country WHERE code = 'PA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.99, (SELECT id FROM country WHERE code = 'PA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(77.33, (SELECT id FROM country WHERE code = 'PA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(80.13, (SELECT id FROM country WHERE code = 'AL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.89, (SELECT id FROM country WHERE code = 'AL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.33, (SELECT id FROM country WHERE code = 'AL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.86, (SELECT id FROM country WHERE code = 'AI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.05, (SELECT id FROM country WHERE code = 'AI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.67, (SELECT id FROM country WHERE code = 'AI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.78, (SELECT id FROM country WHERE code = 'FK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.7, (SELECT id FROM country WHERE code = 'FK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(77.81, (SELECT id FROM country WHERE code = 'FK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.76, (SELECT id FROM country WHERE code = 'US'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.23, (SELECT id FROM country WHERE code = 'US'), (SELECT id FROM sex_type WHERE code = 'female')),
	(77.39, (SELECT id FROM country WHERE code = 'US'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.64, (SELECT id FROM country WHERE code = 'EE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(83.42, (SELECT id FROM country WHERE code = 'EE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.57, (SELECT id FROM country WHERE code = 'EE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.4, (SELECT id FROM country WHERE code = 'SA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.67, (SELECT id FROM country WHERE code = 'SA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(77.78, (SELECT id FROM country WHERE code = 'SA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.23, (SELECT id FROM country WHERE code = 'NC'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.67, (SELECT id FROM country WHERE code = 'NC'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.83, (SELECT id FROM country WHERE code = 'NC'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.22, (SELECT id FROM country WHERE code = 'MP'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.12, (SELECT id FROM country WHERE code = 'MP'), (SELECT id FROM sex_type WHERE code = 'female')),
	(77.59, (SELECT id FROM country WHERE code = 'MP'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.15, (SELECT id FROM country WHERE code = 'PL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.74, (SELECT id FROM country WHERE code = 'PL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.53, (SELECT id FROM country WHERE code = 'PL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.09, (SELECT id FROM country WHERE code = 'HR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.09, (SELECT id FROM country WHERE code = 'HR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.01, (SELECT id FROM country WHERE code = 'HR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.03, (SELECT id FROM country WHERE code = 'WF'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.0, (SELECT id FROM country WHERE code = 'WF'), (SELECT id FROM sex_type WHERE code = 'female')),
	(78.05, (SELECT id FROM country WHERE code = 'WF'), (SELECT id FROM sex_type WHERE code = 'male')),
	(79.02, (SELECT id FROM country WHERE code = 'CN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.78, (SELECT id FROM country WHERE code = 'CN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.38, (SELECT id FROM country WHERE code = 'CN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.81, (SELECT id FROM country WHERE code = 'SK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.98, (SELECT id FROM country WHERE code = 'SK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.6, (SELECT id FROM country WHERE code = 'SK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.62, (SELECT id FROM country WHERE code = 'CU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.0, (SELECT id FROM country WHERE code = 'CU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.25, (SELECT id FROM country WHERE code = 'CU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.62, (SELECT id FROM country WHERE code = 'UY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(82.29, (SELECT id FROM country WHERE code = 'UY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.78, (SELECT id FROM country WHERE code = 'UY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.5, (SELECT id FROM country WHERE code = 'TC'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.72, (SELECT id FROM country WHERE code = 'TC'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.35, (SELECT id FROM country WHERE code = 'TC'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.42, (SELECT id FROM country WHERE code = 'BA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.38, (SELECT id FROM country WHERE code = 'BA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.09, (SELECT id FROM country WHERE code = 'BA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.38, (SELECT id FROM country WHERE code = 'TR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.33, (SELECT id FROM country WHERE code = 'TR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.5, (SELECT id FROM country WHERE code = 'TR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.3, (SELECT id FROM country WHERE code = 'JO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.6, (SELECT id FROM country WHERE code = 'JO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.24, (SELECT id FROM country WHERE code = 'JO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.3, (SELECT id FROM country WHERE code = 'PE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.61, (SELECT id FROM country WHERE code = 'PE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.02, (SELECT id FROM country WHERE code = 'PE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.27, (SELECT id FROM country WHERE code = 'CO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.92, (SELECT id FROM country WHERE code = 'CO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.57, (SELECT id FROM country WHERE code = 'CO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.25, (SELECT id FROM country WHERE code = 'IR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.17, (SELECT id FROM country WHERE code = 'IR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.43, (SELECT id FROM country WHERE code = 'IR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.22, (SELECT id FROM country WHERE code = 'LB'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.11, (SELECT id FROM country WHERE code = 'LB'), (SELECT id FROM sex_type WHERE code = 'female')),
	(76.17, (SELECT id FROM country WHERE code = 'LB'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.11, (SELECT id FROM country WHERE code = 'AG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.75, (SELECT id FROM country WHERE code = 'AG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.12, (SELECT id FROM country WHERE code = 'AG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(78.03, (SELECT id FROM country WHERE code = 'LK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.04, (SELECT id FROM country WHERE code = 'LK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.85, (SELECT id FROM country WHERE code = 'LK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.95, (SELECT id FROM country WHERE code = 'BQ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.6, (SELECT id FROM country WHERE code = 'BQ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.75, (SELECT id FROM country WHERE code = 'BQ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.94, (SELECT id FROM country WHERE code = 'EC'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.62, (SELECT id FROM country WHERE code = 'EC'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.28, (SELECT id FROM country WHERE code = 'EC'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.83, (SELECT id FROM country WHERE code = 'AR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.28, (SELECT id FROM country WHERE code = 'AR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.3, (SELECT id FROM country WHERE code = 'AR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.81, (SELECT id FROM country WHERE code = 'MK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.96, (SELECT id FROM country WHERE code = 'MK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.56, (SELECT id FROM country WHERE code = 'MK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.81, (SELECT id FROM country WHERE code = 'GU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.88, (SELECT id FROM country WHERE code = 'GU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.11, (SELECT id FROM country WHERE code = 'GU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.76, (SELECT id FROM country WHERE code = 'VG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.46, (SELECT id FROM country WHERE code = 'VG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.05, (SELECT id FROM country WHERE code = 'VG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.6, (SELECT id FROM country WHERE code = 'ME'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.74, (SELECT id FROM country WHERE code = 'ME'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.31, (SELECT id FROM country WHERE code = 'ME'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.54, (SELECT id FROM country WHERE code = 'GF'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.44, (SELECT id FROM country WHERE code = 'GF'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.71, (SELECT id FROM country WHERE code = 'GF'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.5, (SELECT id FROM country WHERE code = 'HU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.61, (SELECT id FROM country WHERE code = 'HU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.26, (SELECT id FROM country WHERE code = 'HU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.42, (SELECT id FROM country WHERE code = 'PS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.75, (SELECT id FROM country WHERE code = 'PS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.96, (SELECT id FROM country WHERE code = 'PS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.42, (SELECT id FROM country WHERE code = 'TK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.28, (SELECT id FROM country WHERE code = 'TK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.33, (SELECT id FROM country WHERE code = 'TK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.34, (SELECT id FROM country WHERE code = 'CW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.22, (SELECT id FROM country WHERE code = 'CW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(73.06, (SELECT id FROM country WHERE code = 'CW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.33, (SELECT id FROM country WHERE code = 'RS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.5, (SELECT id FROM country WHERE code = 'RS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.09, (SELECT id FROM country WHERE code = 'RS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.3, (SELECT id FROM country WHERE code = 'SH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.97, (SELECT id FROM country WHERE code = 'SH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.35, (SELECT id FROM country WHERE code = 'SH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.28, (SELECT id FROM country WHERE code = 'PM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.87, (SELECT id FROM country WHERE code = 'PM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(73.34, (SELECT id FROM country WHERE code = 'PM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.16, (SELECT id FROM country WHERE code = 'MY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.82, (SELECT id FROM country WHERE code = 'MY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.81, (SELECT id FROM country WHERE code = 'MY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.1, (SELECT id FROM country WHERE code = 'TN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.68, (SELECT id FROM country WHERE code = 'TN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.55, (SELECT id FROM country WHERE code = 'TN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(77.06, (SELECT id FROM country WHERE code = 'TH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.36, (SELECT id FROM country WHERE code = 'TH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.92, (SELECT id FROM country WHERE code = 'TH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.89, (SELECT id FROM country WHERE code = 'DZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.34, (SELECT id FROM country WHERE code = 'DZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(75.5, (SELECT id FROM country WHERE code = 'DZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.86, (SELECT id FROM country WHERE code = 'SX'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.92, (SELECT id FROM country WHERE code = 'SX'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.17, (SELECT id FROM country WHERE code = 'SX'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.78, (SELECT id FROM country WHERE code = 'AW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.19, (SELECT id FROM country WHERE code = 'AW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.14, (SELECT id FROM country WHERE code = 'AW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.66, (SELECT id FROM country WHERE code = 'MS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.23, (SELECT id FROM country WHERE code = 'MS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.58, (SELECT id FROM country WHERE code = 'MS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.64, (SELECT id FROM country WHERE code = 'BB'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.05, (SELECT id FROM country WHERE code = 'BB'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.09, (SELECT id FROM country WHERE code = 'BB'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.63, (SELECT id FROM country WHERE code = 'LV'), (SELECT id FROM sex_type WHERE code = 'none')),
	(80.85, (SELECT id FROM country WHERE code = 'LV'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.13, (SELECT id FROM country WHERE code = 'LV'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.61, (SELECT id FROM country WHERE code = 'YT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.85, (SELECT id FROM country WHERE code = 'YT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(74.63, (SELECT id FROM country WHERE code = 'YT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.56, (SELECT id FROM country WHERE code = 'CV'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.68, (SELECT id FROM country WHERE code = 'CV'), (SELECT id FROM sex_type WHERE code = 'female')),
	(73.44, (SELECT id FROM country WHERE code = 'CV'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.48, (SELECT id FROM country WHERE code = 'LT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.05, (SELECT id FROM country WHERE code = 'LT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.81, (SELECT id FROM country WHERE code = 'LT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.4, (SELECT id FROM country WHERE code = 'RO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.95, (SELECT id FROM country WHERE code = 'RO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.91, (SELECT id FROM country WHERE code = 'RO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.37, (SELECT id FROM country WHERE code = 'BR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.46, (SELECT id FROM country WHERE code = 'BR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(73.33, (SELECT id FROM country WHERE code = 'BR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.18, (SELECT id FROM country WHERE code = 'AM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.87, (SELECT id FROM country WHERE code = 'AM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.95, (SELECT id FROM country WHERE code = 'AM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.15, (SELECT id FROM country WHERE code = 'VI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(81.73, (SELECT id FROM country WHERE code = 'VI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.17, (SELECT id FROM country WHERE code = 'VI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(76.13, (SELECT id FROM country WHERE code = 'BG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.66, (SELECT id FROM country WHERE code = 'BG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.7, (SELECT id FROM country WHERE code = 'BG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.86, (SELECT id FROM country WHERE code = 'MA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.13, (SELECT id FROM country WHERE code = 'MA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(73.71, (SELECT id FROM country WHERE code = 'MA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.85, (SELECT id FROM country WHERE code = 'CK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.48, (SELECT id FROM country WHERE code = 'CK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.44, (SELECT id FROM country WHERE code = 'CK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.83, (SELECT id FROM country WHERE code = 'BN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.07, (SELECT id FROM country WHERE code = 'BN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(73.81, (SELECT id FROM country WHERE code = 'BN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.67, (SELECT id FROM country WHERE code = 'GD'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.78, (SELECT id FROM country WHERE code = 'GD'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.83, (SELECT id FROM country WHERE code = 'GD'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.63, (SELECT id FROM country WHERE code = 'MX'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.35, (SELECT id FROM country WHERE code = 'MX'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.82, (SELECT id FROM country WHERE code = 'MX'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.47, (SELECT id FROM country WHERE code = 'BD'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.22, (SELECT id FROM country WHERE code = 'BD'), (SELECT id FROM sex_type WHERE code = 'female')),
	(73.82, (SELECT id FROM country WHERE code = 'BD'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.44, (SELECT id FROM country WHERE code = 'MU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.65, (SELECT id FROM country WHERE code = 'MU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.46, (SELECT id FROM country WHERE code = 'MU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.43, (SELECT id FROM country WHERE code = 'NI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.9, (SELECT id FROM country WHERE code = 'NI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.81, (SELECT id FROM country WHERE code = 'NI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.18, (SELECT id FROM country WHERE code = 'LY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.83, (SELECT id FROM country WHERE code = 'LY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.71, (SELECT id FROM country WHERE code = 'LY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.05, (SELECT id FROM country WHERE code = 'VN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.62, (SELECT id FROM country WHERE code = 'VN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.42, (SELECT id FROM country WHERE code = 'VN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.02, (SELECT id FROM country WHERE code = 'UA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.67, (SELECT id FROM country WHERE code = 'UA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.18, (SELECT id FROM country WHERE code = 'UA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(75.01, (SELECT id FROM country WHERE code = 'BS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.59, (SELECT id FROM country WHERE code = 'BS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.37, (SELECT id FROM country WHERE code = 'BS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.98, (SELECT id FROM country WHERE code = 'GE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.49, (SELECT id FROM country WHERE code = 'GE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.11, (SELECT id FROM country WHERE code = 'GE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.97, (SELECT id FROM country WHERE code = 'BY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.52, (SELECT id FROM country WHERE code = 'BY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.14, (SELECT id FROM country WHERE code = 'BY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.89, (SELECT id FROM country WHERE code = 'AZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.6, (SELECT id FROM country WHERE code = 'AZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.02, (SELECT id FROM country WHERE code = 'AZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.81, (SELECT id FROM country WHERE code = 'KZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(78.77, (SELECT id FROM country WHERE code = 'KZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.59, (SELECT id FROM country WHERE code = 'KZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.24, (SELECT id FROM country WHERE code = 'PY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.35, (SELECT id FROM country WHERE code = 'PY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.25, (SELECT id FROM country WHERE code = 'PY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.12, (SELECT id FROM country WHERE code = 'DO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.35, (SELECT id FROM country WHERE code = 'DO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.92, (SELECT id FROM country WHERE code = 'DO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.08, (SELECT id FROM country WHERE code = 'BZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.0, (SELECT id FROM country WHERE code = 'BZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.4, (SELECT id FROM country WHERE code = 'BZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(74.04, (SELECT id FROM country WHERE code = 'SR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.26, (SELECT id FROM country WHERE code = 'SR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.87, (SELECT id FROM country WHERE code = 'SR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.98, (SELECT id FROM country WHERE code = 'KP'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.16, (SELECT id FROM country WHERE code = 'KP'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.77, (SELECT id FROM country WHERE code = 'KP'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.89, (SELECT id FROM country WHERE code = 'TT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.1, (SELECT id FROM country WHERE code = 'TT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.77, (SELECT id FROM country WHERE code = 'TT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.8, (SELECT id FROM country WHERE code = 'BT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(75.84, (SELECT id FROM country WHERE code = 'BT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(72.08, (SELECT id FROM country WHERE code = 'BT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.7, (SELECT id FROM country WHERE code = 'RU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(79.46, (SELECT id FROM country WHERE code = 'RU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.91, (SELECT id FROM country WHERE code = 'RU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.43, (SELECT id FROM country WHERE code = 'SY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(75.91, (SELECT id FROM country WHERE code = 'SY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.96, (SELECT id FROM country WHERE code = 'SY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.39, (SELECT id FROM country WHERE code = 'TO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.84, (SELECT id FROM country WHERE code = 'TO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.79, (SELECT id FROM country WHERE code = 'TO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.39, (SELECT id FROM country WHERE code = 'HN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.03, (SELECT id FROM country WHERE code = 'HN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.8, (SELECT id FROM country WHERE code = 'HN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.28, (SELECT id FROM country WHERE code = 'SC'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.98, (SELECT id FROM country WHERE code = 'SC'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.37, (SELECT id FROM country WHERE code = 'SC'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.25, (SELECT id FROM country WHERE code = 'AS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.28, (SELECT id FROM country WHERE code = 'AS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.55, (SELECT id FROM country WHERE code = 'AS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.15, (SELECT id FROM country WHERE code = 'LC'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.75, (SELECT id FROM country WHERE code = 'LC'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.74, (SELECT id FROM country WHERE code = 'LC'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.04, (SELECT id FROM country WHERE code = 'GT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(75.37, (SELECT id FROM country WHERE code = 'GT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.71, (SELECT id FROM country WHERE code = 'GT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(73.01, (SELECT id FROM country WHERE code = 'VE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.99, (SELECT id FROM country WHERE code = 'VE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.22, (SELECT id FROM country WHERE code = 'VE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.78, (SELECT id FROM country WHERE code = 'UZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(75.84, (SELECT id FROM country WHERE code = 'UZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.79, (SELECT id FROM country WHERE code = 'UZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.74, (SELECT id FROM country WHERE code = 'SV'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.91, (SELECT id FROM country WHERE code = 'SV'), (SELECT id FROM sex_type WHERE code = 'female')),
	(68.23, (SELECT id FROM country WHERE code = 'SV'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.72, (SELECT id FROM country WHERE code = 'IN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.39, (SELECT id FROM country WHERE code = 'IN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(71.16, (SELECT id FROM country WHERE code = 'IN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.63, (SELECT id FROM country WHERE code = 'IQ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.45, (SELECT id FROM country WHERE code = 'IQ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.67, (SELECT id FROM country WHERE code = 'IQ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.58, (SELECT id FROM country WHERE code = 'KN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(76.44, (SELECT id FROM country WHERE code = 'KN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(68.96, (SELECT id FROM country WHERE code = 'KN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.49, (SELECT id FROM country WHERE code = 'MN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(77.11, (SELECT id FROM country WHERE code = 'MN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(68.01, (SELECT id FROM country WHERE code = 'MN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.19, (SELECT id FROM country WHERE code = 'TJ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.45, (SELECT id FROM country WHERE code = 'TJ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.89, (SELECT id FROM country WHERE code = 'TJ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.16, (SELECT id FROM country WHERE code = 'EG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.41, (SELECT id FROM country WHERE code = 'EG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.98, (SELECT id FROM country WHERE code = 'EG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.11, (SELECT id FROM country WHERE code = 'KG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(75.7, (SELECT id FROM country WHERE code = 'KG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(68.56, (SELECT id FROM country WHERE code = 'KG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.08, (SELECT id FROM country WHERE code = 'WS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.14, (SELECT id FROM country WHERE code = 'WS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.17, (SELECT id FROM country WHERE code = 'WS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(72.02, (SELECT id FROM country WHERE code = 'VU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.49, (SELECT id FROM country WHERE code = 'VU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.89, (SELECT id FROM country WHERE code = 'VU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.98, (SELECT id FROM country WHERE code = 'EH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.22, (SELECT id FROM country WHERE code = 'EH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(70.24, (SELECT id FROM country WHERE code = 'EH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.86, (SELECT id FROM country WHERE code = 'JM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.45, (SELECT id FROM country WHERE code = 'JM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.27, (SELECT id FROM country WHERE code = 'JM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.65, (SELECT id FROM country WHERE code = 'VC'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.78, (SELECT id FROM country WHERE code = 'VC'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.01, (SELECT id FROM country WHERE code = 'VC'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.62, (SELECT id FROM country WHERE code = 'DM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(75.06, (SELECT id FROM country WHERE code = 'DM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(68.63, (SELECT id FROM country WHERE code = 'DM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.6, (SELECT id FROM country WHERE code = 'MD'), (SELECT id FROM sex_type WHERE code = 'none')),
	(75.93, (SELECT id FROM country WHERE code = 'MD'), (SELECT id FROM sex_type WHERE code = 'female')),
	(66.96, (SELECT id FROM country WHERE code = 'MD'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.58, (SELECT id FROM country WHERE code = 'ID'), (SELECT id FROM sex_type WHERE code = 'none')),
	(73.77, (SELECT id FROM country WHERE code = 'ID'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.42, (SELECT id FROM country WHERE code = 'ID'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.16, (SELECT id FROM country WHERE code = 'NP'), (SELECT id FROM sex_type WHERE code = 'none')),
	(72.7, (SELECT id FROM country WHERE code = 'NP'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.56, (SELECT id FROM country WHERE code = 'NP'), (SELECT id FROM sex_type WHERE code = 'male')),
	(71.14, (SELECT id FROM country WHERE code = 'KH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(73.72, (SELECT id FROM country WHERE code = 'KH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(68.45, (SELECT id FROM country WHERE code = 'KH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(70.98, (SELECT id FROM country WHERE code = 'SB'), (SELECT id FROM sex_type WHERE code = 'none')),
	(72.52, (SELECT id FROM country WHERE code = 'SB'), (SELECT id FROM sex_type WHERE code = 'female')),
	(69.58, (SELECT id FROM country WHERE code = 'SB'), (SELECT id FROM sex_type WHERE code = 'male')),
	(70.57, (SELECT id FROM country WHERE code = 'GY'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.35, (SELECT id FROM country WHERE code = 'GY'), (SELECT id FROM sex_type WHERE code = 'female')),
	(66.84, (SELECT id FROM country WHERE code = 'GY'), (SELECT id FROM sex_type WHERE code = 'male')),
	(70.45, (SELECT id FROM country WHERE code = 'TM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(73.33, (SELECT id FROM country WHERE code = 'TM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.24, (SELECT id FROM country WHERE code = 'TM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(70.44, (SELECT id FROM country WHERE code = 'GL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(72.89, (SELECT id FROM country WHERE code = 'GL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(68.42, (SELECT id FROM country WHERE code = 'GL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(70.36, (SELECT id FROM country WHERE code = 'NU'), (SELECT id FROM sex_type WHERE code = 'none')),
	(73.17, (SELECT id FROM country WHERE code = 'NU'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.75, (SELECT id FROM country WHERE code = 'NU'), (SELECT id FROM sex_type WHERE code = 'male')),
	(70.26, (SELECT id FROM country WHERE code = 'ST'), (SELECT id FROM sex_type WHERE code = 'none')),
	(74.26, (SELECT id FROM country WHERE code = 'ST'), (SELECT id FROM sex_type WHERE code = 'female')),
	(66.73, (SELECT id FROM country WHERE code = 'ST'), (SELECT id FROM sex_type WHERE code = 'male')),
	(70.17, (SELECT id FROM country WHERE code = 'PH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(73.23, (SELECT id FROM country WHERE code = 'PH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.2, (SELECT id FROM country WHERE code = 'PH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.73, (SELECT id FROM country WHERE code = 'YE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.88, (SELECT id FROM country WHERE code = 'YE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.63, (SELECT id FROM country WHERE code = 'YE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.7, (SELECT id FROM country WHERE code = 'LA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(72.05, (SELECT id FROM country WHERE code = 'LA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.47, (SELECT id FROM country WHERE code = 'LA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.61, (SELECT id FROM country WHERE code = 'PW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(72.23, (SELECT id FROM country WHERE code = 'PW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.44, (SELECT id FROM country WHERE code = 'PW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.57, (SELECT id FROM country WHERE code = 'BW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(72.17, (SELECT id FROM country WHERE code = 'BW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.03, (SELECT id FROM country WHERE code = 'BW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.4, (SELECT id FROM country WHERE code = 'ER'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.48, (SELECT id FROM country WHERE code = 'ER'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.23, (SELECT id FROM country WHERE code = 'ER'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.39, (SELECT id FROM country WHERE code = 'SN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.51, (SELECT id FROM country WHERE code = 'SN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.42, (SELECT id FROM country WHERE code = 'SN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.16, (SELECT id FROM country WHERE code = 'MR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.2, (SELECT id FROM country WHERE code = 'MR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(67.09, (SELECT id FROM country WHERE code = 'MR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(69.06, (SELECT id FROM country WHERE code = 'BO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.69, (SELECT id FROM country WHERE code = 'BO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(66.56, (SELECT id FROM country WHERE code = 'BO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(68.92, (SELECT id FROM country WHERE code = 'UG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.83, (SELECT id FROM country WHERE code = 'UG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(65.9, (SELECT id FROM country WHERE code = 'UG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(68.88, (SELECT id FROM country WHERE code = 'GA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.64, (SELECT id FROM country WHERE code = 'GA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(66.4, (SELECT id FROM country WHERE code = 'GA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(68.47, (SELECT id FROM country WHERE code = 'RW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(70.63, (SELECT id FROM country WHERE code = 'RW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(66.12, (SELECT id FROM country WHERE code = 'RW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(68.33, (SELECT id FROM country WHERE code = 'TL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(70.14, (SELECT id FROM country WHERE code = 'TL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(66.66, (SELECT id FROM country WHERE code = 'TL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(68.15, (SELECT id FROM country WHERE code = 'ET'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.58, (SELECT id FROM country WHERE code = 'ET'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.88, (SELECT id FROM country WHERE code = 'ET'), (SELECT id FROM sex_type WHERE code = 'male')),
	(68.06, (SELECT id FROM country WHERE code = 'PK'), (SELECT id FROM sex_type WHERE code = 'none')),
	(70.61, (SELECT id FROM country WHERE code = 'PK'), (SELECT id FROM sex_type WHERE code = 'female')),
	(65.69, (SELECT id FROM country WHERE code = 'PK'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.92, (SELECT id FROM country WHERE code = 'MW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.14, (SELECT id FROM country WHERE code = 'MW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.61, (SELECT id FROM country WHERE code = 'MW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.81, (SELECT id FROM country WHERE code = 'NA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.78, (SELECT id FROM country WHERE code = 'NA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(63.73, (SELECT id FROM country WHERE code = 'NA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.77, (SELECT id FROM country WHERE code = 'FJ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(69.9, (SELECT id FROM country WHERE code = 'FJ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(65.73, (SELECT id FROM country WHERE code = 'FJ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.65, (SELECT id FROM country WHERE code = 'FM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.57, (SELECT id FROM country WHERE code = 'FM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(63.9, (SELECT id FROM country WHERE code = 'FM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.63, (SELECT id FROM country WHERE code = 'TZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(70.44, (SELECT id FROM country WHERE code = 'TZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.78, (SELECT id FROM country WHERE code = 'TZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.56, (SELECT id FROM country WHERE code = 'TV'), (SELECT id FROM sex_type WHERE code = 'none')),
	(71.19, (SELECT id FROM country WHERE code = 'TV'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.2, (SELECT id FROM country WHERE code = 'TV'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.5, (SELECT id FROM country WHERE code = 'MM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(70.8, (SELECT id FROM country WHERE code = 'MM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.37, (SELECT id FROM country WHERE code = 'MM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.48, (SELECT id FROM country WHERE code = 'KM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(69.69, (SELECT id FROM country WHERE code = 'KM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(65.43, (SELECT id FROM country WHERE code = 'KM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(67.32, (SELECT id FROM country WHERE code = 'MH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(69.76, (SELECT id FROM country WHERE code = 'MH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(65.21, (SELECT id FROM country WHERE code = 'MH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.89, (SELECT id FROM country WHERE code = 'SD'), (SELECT id FROM sex_type WHERE code = 'none')),
	(70.21, (SELECT id FROM country WHERE code = 'SD'), (SELECT id FROM sex_type WHERE code = 'female')),
	(63.78, (SELECT id FROM country WHERE code = 'SD'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.88, (SELECT id FROM country WHERE code = 'ZM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(69.27, (SELECT id FROM country WHERE code = 'ZM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.42, (SELECT id FROM country WHERE code = 'ZM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.86, (SELECT id FROM country WHERE code = 'KI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(68.63, (SELECT id FROM country WHERE code = 'KI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.91, (SELECT id FROM country WHERE code = 'KI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.77, (SELECT id FROM country WHERE code = 'AF'), (SELECT id FROM sex_type WHERE code = 'none')),
	(68.33, (SELECT id FROM country WHERE code = 'AF'), (SELECT id FROM sex_type WHERE code = 'female')),
	(65.15, (SELECT id FROM country WHERE code = 'AF'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.66, (SELECT id FROM country WHERE code = 'ZA'), (SELECT id FROM sex_type WHERE code = 'none')),
	(70.16, (SELECT id FROM country WHERE code = 'ZA'), (SELECT id FROM sex_type WHERE code = 'female')),
	(63.12, (SELECT id FROM country WHERE code = 'ZA'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.61, (SELECT id FROM country WHERE code = 'DJ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(69.18, (SELECT id FROM country WHERE code = 'DJ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.11, (SELECT id FROM country WHERE code = 'DJ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.5, (SELECT id FROM country WHERE code = 'PG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(69.47, (SELECT id FROM country WHERE code = 'PG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.04, (SELECT id FROM country WHERE code = 'PG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.45, (SELECT id FROM country WHERE code = 'GM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(68.18, (SELECT id FROM country WHERE code = 'GM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.71, (SELECT id FROM country WHERE code = 'GM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.42, (SELECT id FROM country WHERE code = 'CG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(68.17, (SELECT id FROM country WHERE code = 'CG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(64.7, (SELECT id FROM country WHERE code = 'CG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(66.08, (SELECT id FROM country WHERE code = 'GH'), (SELECT id FROM sex_type WHERE code = 'none')),
	(68.57, (SELECT id FROM country WHERE code = 'GH'), (SELECT id FROM sex_type WHERE code = 'female')),
	(63.67, (SELECT id FROM country WHERE code = 'GH'), (SELECT id FROM sex_type WHERE code = 'male')),
	(65.45, (SELECT id FROM country WHERE code = 'HT'), (SELECT id FROM sex_type WHERE code = 'none')),
	(68.83, (SELECT id FROM country WHERE code = 'HT'), (SELECT id FROM sex_type WHERE code = 'female')),
	(62.21, (SELECT id FROM country WHERE code = 'HT'), (SELECT id FROM sex_type WHERE code = 'male')),
	(65.17, (SELECT id FROM country WHERE code = 'AO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(67.73, (SELECT id FROM country WHERE code = 'AO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(62.62, (SELECT id FROM country WHERE code = 'AO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.59, (SELECT id FROM country WHERE code = 'GW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(66.91, (SELECT id FROM country WHERE code = 'GW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(62.13, (SELECT id FROM country WHERE code = 'GW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.54, (SELECT id FROM country WHERE code = 'SZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(67.41, (SELECT id FROM country WHERE code = 'SZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(61.58, (SELECT id FROM country WHERE code = 'SZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.51, (SELECT id FROM country WHERE code = 'CM'), (SELECT id FROM sex_type WHERE code = 'none')),
	(66.79, (SELECT id FROM country WHERE code = 'CM'), (SELECT id FROM sex_type WHERE code = 'female')),
	(62.3, (SELECT id FROM country WHERE code = 'CM'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.3, (SELECT id FROM country WHERE code = 'GQ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(66.33, (SELECT id FROM country WHERE code = 'GQ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(62.59, (SELECT id FROM country WHERE code = 'GQ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.25, (SELECT id FROM country WHERE code = 'MG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(66.06, (SELECT id FROM country WHERE code = 'MG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(62.51, (SELECT id FROM country WHERE code = 'MG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.19, (SELECT id FROM country WHERE code = 'KE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(66.51, (SELECT id FROM country WHERE code = 'KE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(61.96, (SELECT id FROM country WHERE code = 'KE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.14, (SELECT id FROM country WHERE code = 'MZ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(67.11, (SELECT id FROM country WHERE code = 'MZ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(60.83, (SELECT id FROM country WHERE code = 'MZ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(64.14, (SELECT id FROM country WHERE code = 'BI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(66.24, (SELECT id FROM country WHERE code = 'BI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(62.04, (SELECT id FROM country WHERE code = 'BI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(63.63, (SELECT id FROM country WHERE code = 'ZW'), (SELECT id FROM sex_type WHERE code = 'none')),
	(65.9, (SELECT id FROM country WHERE code = 'ZW'), (SELECT id FROM sex_type WHERE code = 'female')),
	(61.01, (SELECT id FROM country WHERE code = 'ZW'), (SELECT id FROM sex_type WHERE code = 'male')),
	(63.33, (SELECT id FROM country WHERE code = 'TG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(63.61, (SELECT id FROM country WHERE code = 'TG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(63.03, (SELECT id FROM country WHERE code = 'TG'), (SELECT id FROM sex_type WHERE code = 'male')),
	(62.62, (SELECT id FROM country WHERE code = 'LR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(63.97, (SELECT id FROM country WHERE code = 'LR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(61.27, (SELECT id FROM country WHERE code = 'LR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(62.61, (SELECT id FROM country WHERE code = 'NR'), (SELECT id FROM sex_type WHERE code = 'none')),
	(64.55, (SELECT id FROM country WHERE code = 'NR'), (SELECT id FROM sex_type WHERE code = 'female')),
	(60.68, (SELECT id FROM country WHERE code = 'NR'), (SELECT id FROM sex_type WHERE code = 'male')),
	(62.44, (SELECT id FROM country WHERE code = 'CI'), (SELECT id FROM sex_type WHERE code = 'none')),
	(64.66, (SELECT id FROM country WHERE code = 'CI'), (SELECT id FROM sex_type WHERE code = 'female')),
	(60.47, (SELECT id FROM country WHERE code = 'CI'), (SELECT id FROM sex_type WHERE code = 'male')),
	(62.39, (SELECT id FROM country WHERE code = 'CD'), (SELECT id FROM sex_type WHERE code = 'none')),
	(64.57, (SELECT id FROM country WHERE code = 'CD'), (SELECT id FROM sex_type WHERE code = 'female')),
	(60.25, (SELECT id FROM country WHERE code = 'CD'), (SELECT id FROM sex_type WHERE code = 'male')),
	(62.33, (SELECT id FROM country WHERE code = 'SL'), (SELECT id FROM sex_type WHERE code = 'none')),
	(64.09, (SELECT id FROM country WHERE code = 'SL'), (SELECT id FROM sex_type WHERE code = 'female')),
	(60.57, (SELECT id FROM country WHERE code = 'SL'), (SELECT id FROM sex_type WHERE code = 'male')),
	(61.88, (SELECT id FROM country WHERE code = 'NE'), (SELECT id FROM sex_type WHERE code = 'none')),
	(62.9, (SELECT id FROM country WHERE code = 'NE'), (SELECT id FROM sex_type WHERE code = 'female')),
	(60.9, (SELECT id FROM country WHERE code = 'NE'), (SELECT id FROM sex_type WHERE code = 'male')),
	(61.65, (SELECT id FROM country WHERE code = 'BF'), (SELECT id FROM sex_type WHERE code = 'none')),
	(63.81, (SELECT id FROM country WHERE code = 'BF'), (SELECT id FROM sex_type WHERE code = 'female')),
	(59.45, (SELECT id FROM country WHERE code = 'BF'), (SELECT id FROM sex_type WHERE code = 'male')),
	(61.32, (SELECT id FROM country WHERE code = 'BJ'), (SELECT id FROM sex_type WHERE code = 'none')),
	(62.81, (SELECT id FROM country WHERE code = 'BJ'), (SELECT id FROM sex_type WHERE code = 'female')),
	(59.84, (SELECT id FROM country WHERE code = 'BJ'), (SELECT id FROM sex_type WHERE code = 'male')),
	(61.23, (SELECT id FROM country WHERE code = 'GN'), (SELECT id FROM sex_type WHERE code = 'none')),
	(62.45, (SELECT id FROM country WHERE code = 'GN'), (SELECT id FROM sex_type WHERE code = 'female')),
	(59.95, (SELECT id FROM country WHERE code = 'GN'), (SELECT id FROM sex_type WHERE code = 'male')),
	(61.11, (SELECT id FROM country WHERE code = 'ML'), (SELECT id FROM sex_type WHERE code = 'none')),
	(62.62, (SELECT id FROM country WHERE code = 'ML'), (SELECT id FROM sex_type WHERE code = 'female')),
	(59.66, (SELECT id FROM country WHERE code = 'ML'), (SELECT id FROM sex_type WHERE code = 'male')),
	(59.26, (SELECT id FROM country WHERE code = 'SO'), (SELECT id FROM sex_type WHERE code = 'none')),
	(61.86, (SELECT id FROM country WHERE code = 'SO'), (SELECT id FROM sex_type WHERE code = 'female')),
	(56.77, (SELECT id FROM country WHERE code = 'SO'), (SELECT id FROM sex_type WHERE code = 'male')),
	(58.63, (SELECT id FROM country WHERE code = 'LS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(61.29, (SELECT id FROM country WHERE code = 'LS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(55.85, (SELECT id FROM country WHERE code = 'LS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(58.15, (SELECT id FROM country WHERE code = 'CF'), (SELECT id FROM sex_type WHERE code = 'none')),
	(60.06, (SELECT id FROM country WHERE code = 'CF'), (SELECT id FROM sex_type WHERE code = 'female')),
	(55.97, (SELECT id FROM country WHERE code = 'CF'), (SELECT id FROM sex_type WHERE code = 'male')),
	(57.97, (SELECT id FROM country WHERE code = 'SS'), (SELECT id FROM sex_type WHERE code = 'none')),
	(60.98, (SELECT id FROM country WHERE code = 'SS'), (SELECT id FROM sex_type WHERE code = 'female')),
	(54.99, (SELECT id FROM country WHERE code = 'SS'), (SELECT id FROM sex_type WHERE code = 'male')),
	(55.58, (SELECT id FROM country WHERE code = 'TD'), (SELECT id FROM sex_type WHERE code = 'none')),
	(57.56, (SELECT id FROM country WHERE code = 'TD'), (SELECT id FROM sex_type WHERE code = 'female')),
	(53.68, (SELECT id FROM country WHERE code = 'TD'), (SELECT id FROM sex_type WHERE code = 'male')),
	(54.95, (SELECT id FROM country WHERE code = 'NG'), (SELECT id FROM sex_type WHERE code = 'none')),
	(55.3, (SELECT id FROM country WHERE code = 'NG'), (SELECT id FROM sex_type WHERE code = 'female')),
	(54.6, (SELECT id FROM country WHERE code = 'NG'), (SELECT id FROM sex_type WHERE code = 'male'));

-- habits
INSERT INTO smoking_type (code, title, adjustment_years) VALUES
    ('non_smoker', 'Non-smoker', 0),
    ('former_smoker', 'Former smoker', -2),
    ('light_smoker', 'Light smoker', -5),
    ('heavy_smoker', 'Heavy smoker', -9);

INSERT INTO physical_activity_type (code, title, adjustment_years) VALUES
    ('active', 'Active (>= 3 METs/day)', 2.5),
    ('moderate', 'Moderate', 0),
    ('sedentary', 'Sedentary', -2.5);

INSERT INTO diet_quality_type (code, title, adjustment_years) VALUES
    ('healthy', 'Healthy diet', 2),
    ('average', 'Average diet', 0),
    ('poor', 'Poor diet', -2);

INSERT INTO alcohol_consumption_type (code, title, adjustment_years) VALUES
    ('moderate', 'Moderate', 0),
    ('none', 'None', 0),
    ('heavy', 'Heavy drinking', -1.5);

-- life stage range
INSERT INTO life_stage_range (stage_no, title, beginning_age, ending_age) VALUES
    (1, 'Infancy', 0, 2),
    (2, 'Childhood', 3, 8),
    (3, 'Adolescence', 9, 18),
    (4, 'Early Adulthood', 19, 45),
    (5, 'Middle Adulthood', 46, 65),
    (6, 'Later Adulthood', 66, NULL);

-- post-ffp asset
INSERT INTO asset_type (code, title) VALUES
    ('pension', 'Pension Income'),
    ('rental', 'Rental Income'),
    ('other', 'Other Passive Income');

-- scenario
INSERT INTO scenario_type (no, title, description) VALUES
    (1, 'SRP Goal Feasibility',
    'Can I reach my Safe Retirement (SRP) goal?'),

    (2, 'SRP Age Estimation',
    'When will I reach Safe Retirement (SRP)?'),

    (3, 'Spending at SRP',
    'How much can I spend at Safe Retirement (SRP)?'),

    (4, 'Required Savings',
    'How much should I save to reach Safe Retirement (SRP)?');