type ValueOf<T> = T[keyof T];
type NestedValueOf<T> = ValueOf<{
  [K in keyof T]: ValueOf<T[K]>;
}>;

export const ERROR_CODES = {
  VALIDATION: {
    INVALID_INPUT: 'VALIDATION.INVALID_INPUT',
    FIELD_INVALID: 'VALIDATION.FIELD_INVALID',
    INVALID_JSON: 'VALIDATION.INVALID_JSON',
    BAD_REQUEST: 'VALIDATION.BAD_REQUEST',
  },
  AUTH: {
    UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
    FORBIDDEN: 'AUTH.FORBIDDEN',
    NO_TOKEN: 'AUTH.NO_TOKEN',
    INVALID_TOKEN: 'AUTH.INVALID_TOKEN',
    INVALID_CSRF_TOKEN: 'AUTH.INVALID_CSRF_TOKEN',
    MISSING_REFRESH_TOKEN: 'AUTH.MISSING_REFRESH_TOKEN',
    EMAIL_EXISTS: 'AUTH.EMAIL_EXISTS',
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    EMAIL_NOT_VERIFIED: 'AUTH.EMAIL_NOT_VERIFIED',
    INVALID_OR_EXPIRED_TOKEN: 'AUTH.INVALID_OR_EXPIRED_TOKEN',
    CURRENT_PASSWORD_INCORRECT: 'AUTH.CURRENT_PASSWORD_INCORRECT',
    NEW_PASSWORD_REUSED: 'AUTH.NEW_PASSWORD_REUSED',
    INVALID_REFRESH_TOKEN: 'AUTH.INVALID_REFRESH_TOKEN',
  },
  RATE_LIMIT: {
    AUTH: 'RATE_LIMIT.AUTH',
    EMAIL_VERIFICATION: 'RATE_LIMIT.EMAIL_VERIFICATION',
    PASSWORD_RESET: 'RATE_LIMIT.PASSWORD_RESET',
  },
  SYSTEM: {
    ERROR: 'SYSTEM.ERROR',
    UNKNOWN: 'SYSTEM.UNKNOWN',
    NOT_FOUND: 'SYSTEM.NOT_FOUND',
    ROUTE_NOT_FOUND: 'SYSTEM.ROUTE_NOT_FOUND',
    INTERNAL_ERROR: 'SYSTEM.INTERNAL_ERROR',
  },
} as const;

export type ErrorCode = NestedValueOf<typeof ERROR_CODES>;
